import { escapeHtml as e, form, hidden } from "./ui";

export function ownerSetup(origin: string, token: string, recovery: boolean) {
  return `<p class="lead">${recovery ? "Choose a new password for" : "Create a password to protect"} the Publisher running in your Cloudflare account.</p><div class="identity"><span>Your private Publisher</span><strong>${e(new URL(origin).hostname)}</strong><p>This password signs you in to this control panel, hosted in your Cloudflare account.</p></div><form method="post">${hidden("token", token)}<label for="owner-password">${recovery ? "New password" : "Owner password"}</label><input id="owner-password" type="password" name="password" minlength="12" maxlength="256" autocomplete="new-password" aria-describedby="password-help" required><p id="password-help" class="help">Use at least 12 characters. Your password manager can generate and save one for this address.</p><button>${recovery ? "Save new password" : "Create password and open Publisher"}</button></form><p class="help">Next: connect website publishing in Settings, then add this Publisher to ChatGPT.</p>`;
}

export function cloudflareSettings(
  origin: string,
  account: string,
  csrf: string,
  connected = false,
) {
  return `<section id="settings" class="panel settings-panel"><div class="panel-heading"><h2>Cloudflare settings</h2><span class="status ${connected ? "live" : ""}">${connected ? "Connected" : "Setup needed"}</span></div><div class="panel-scroll" tabindex="0" role="region" aria-label="Cloudflare settings"><p>Your websites run in your account. Your publishing key stays encrypted inside this Publisher.</p><details ${connected ? "" : "open"}><summary>${connected ? "Replace publishing key" : "Connect website publishing"}</summary><p>The approval during installation let Jumper MCP create this Publisher. That temporary access has ended. Add a Cloudflare API token so your Publisher can create and update websites.</p><details class="token-guide"><summary>Create your publishing key</summary><ol><li>Open <a href="https://dash.cloudflare.com/profile/api-tokens" target="_blank" rel="noreferrer">Cloudflare → My Profile → API Tokens</a> and select <strong>Create Token → Create Custom Token</strong>.</li><li>Name it <strong>Publisher websites</strong>.</li><li>Under Permissions, select <strong>Account → Workers Scripts → Edit</strong>. If your dashboard uses the newer Workers roles, choose <strong>Workers → Admin</strong> at product level so Publisher can create new website Workers. <a href="https://developers.cloudflare.com/workers/authorization/workers/" target="_blank" rel="noreferrer">Cloudflare’s permission guide</a></li><li>Under Account Resources, select <strong>Include → Specific account</strong> and choose the account hosting this Publisher. Its account ID is <code>${e(account)}</code>.</li><li>Select <strong>Continue to summary → Create Token</strong>. Copy the token and paste it into the field below.</li></ol><p class="help">Keep the token in this Publisher. Do not paste it into ChatGPT or the Jumper MCP installer. You can revoke it later in Cloudflare’s API Tokens page.</p></details>${form("/credentials", csrf, '<label for="cloudflare-token">Cloudflare API token</label><input id="cloudflare-token" type="password" name="token" autocomplete="off" required><button>Connect website publishing</button>')}</details><details><summary>Account details</summary><p>Cloudflare account</p><code>${e(account)}</code><p>Publisher address</p><code>${e(origin)}</code></details></div></section>`;
}

export function ownerLogin(returnTo = "/", error = "") {
  const destination = returnTo.startsWith("/authorize?") ? returnTo : "/";
  return `${error ? `<p role="alert">${e(error)}</p>` : ""}<form method="post" action="/login">${hidden("return_to", destination)}<label>Owner password<input type="password" name="password" autocomplete="current-password" required></label><button>${destination === "/" ? "Sign in" : "Continue to consent"}</button></form><p>Use the owner password you created for this Publisher.</p><p><a href="/">Return to Publisher</a></p>`;
}
