import { escapeHtml as e, form, hidden } from "./ui";

export function ownerSetup(origin: string, token: string, recovery: boolean) {
  return `<p class="lead">${recovery ? "Choose a new password for" : "Create a password to protect"} the Publisher running in your Cloudflare account.</p><div class="identity"><span>Your private Publisher</span><strong>${e(new URL(origin).hostname)}</strong><p>This password signs you in to this control panel, hosted in your Cloudflare account.</p></div><form method="post">${hidden("token", token)}<label for="owner-password">${recovery ? "New password" : "Owner password"}</label><input id="owner-password" type="password" name="password" minlength="12" maxlength="256" autocomplete="new-password" aria-describedby="password-help" required><p id="password-help" class="help">Use at least 12 characters. Your password manager can generate and save one for this address.</p><button>${recovery ? "Save new password" : "Create password and open Publisher"}</button></form><p class="help">Next: connect website publishing in Settings, then add this Publisher to ChatGPT.</p>`;
}

export function cloudflareSettings(
  origin: string,
  account: string,
  csrf: string,
  receipt: unknown,
) {
  return `<section id="settings"><p class="eyebrow">Settings</p><h2>Cloudflare</h2><p>The Cloudflare approval during installation let Jumper MCP create this Publisher. That temporary installer access has ended. Your Publisher needs its own key to create and update websites when you ask it to publish.</p><p>Cloudflare calls this key an <strong>API token</strong>. Create it for the account below, then save it here. It is encrypted and stored inside your Publisher in your Cloudflare account.</p><details class="token-guide" open><summary>Create your publishing key</summary><ol><li>Open <a href="https://dash.cloudflare.com/profile/api-tokens" target="_blank" rel="noreferrer">Cloudflare → My Profile → API Tokens</a> and select <strong>Create Token → Create Custom Token</strong>.</li><li>Name it <strong>Publisher websites</strong>.</li><li>Under Permissions, select <strong>Account → Workers Scripts → Edit</strong>. If your dashboard uses the newer Workers roles, choose <strong>Workers → Admin</strong> at product level so Publisher can create new website Workers. <a href="https://developers.cloudflare.com/workers/authorization/workers/" target="_blank" rel="noreferrer">Cloudflare’s permission guide</a></li><li>Under Account Resources, select <strong>Include → Specific account</strong> and choose the account hosting this Publisher. Its account ID is <code>${e(account)}</code>.</li><li>Select <strong>Continue to summary → Create Token</strong>. Copy the token and paste it into the field below.</li></ol><p class="help">Keep the token in this Publisher. Do not paste it into ChatGPT or the Jumper MCP installer. You can revoke it later in Cloudflare’s API Tokens page.</p></details>${form("/credentials", csrf, '<label for="cloudflare-token">Cloudflare API token</label><input id="cloudflare-token" type="password" name="token" autocomplete="off" required><button>Connect website publishing</button>')}<div id="installation-receipt"><h3>Installation receipt</h3><p>This receipt records the Publisher installed in your Cloudflare account.</p><label for="mcp-url">MCP server URL</label><input id="mcp-url" type="text" readonly value="${e(origin)}/mcp"><p class="help">In ChatGPT → Plugins, click “Add custom MCP server” and paste this URL. If that option is missing, check Settings → Security and login → Developer mode. Availability depends on your ChatGPT account and workspace.</p><details><summary>Technical installation details</summary><pre>${e(JSON.stringify(receipt, null, 2))}</pre></details></div></section>`;
}
